# Tensor Creation
In order to get anything done, we need some way to store and manipulate data. Let’s get our hands dirty with n-dimensional arrays, which we also call tensors. The `Tensor` class resembles NumPy`s ndarray with some new features.
- **Vector** - one dimensional tensor.
- **Matrix** - two dimensional tensor.
- **k-th order tensor** - for k-dimensional tensor.

In [19]:
import torch

PyTorch provides a variety of functions for creating new tensors prepopulated with values. By invoking arange(n), we can create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included). By default, the interval size is 1. Unless otherwise specified, new tensors are stored in main memory and designated for CPU-based computation.

In [20]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
x.numel()

12

In [22]:
x.shape

torch.Size([12])

We can change the shape of a tensor without altering its size or values, by invoking reshape. For example, we can transform our vector x whose shape is (12,) to a matrix X with shape (3, 4). This new tensor retains all elements but reconfigures them into a matrix. Notice that the elements of our vector are laid out one row at a time and thus x[3] == X[0, 3].

Note that specifying every shape component to reshape is redundant. Because we already know our tensor’s size, we can work out one component of the shape given the rest. We can place a -1 for the shape component that should be inferred automatically.

In [23]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X[1][2]

tensor(6.)

In [25]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We often wish to sample each element randomly (and independently) from a given probability distribution. For example, the parameters of neural networks are often initialized randomly. The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.

In [27]:
torch.randn((3, 4))

tensor([[ 0.5236, -2.7086, -0.7330,  0.1982],
        [-1.0343, -0.5450,  0.5693, -0.1931],
        [-1.0654, -0.9272,  0.6971,  0.5820]])

Finally, we can construct tensors by supplying the exact values for each element.

In [28]:
torch.tensor([[1, 2, 3, 4], [5, 5, 6, 6], [22, 25, 35, 40]])

tensor([[ 1,  2,  3,  4],
        [ 5,  5,  6,  6],
        [22, 25, 35, 40]])